name: Andrei Rodionov

# Site settings
title:
  en: The site title
  ru: Заголовок сайта

index:
  en:
  ru: index_ru.html

permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
